blog/blog/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import admin
from django.views.generic.edit import CreateView
from myapp.views import *
from myapp.forms import AuthorCreate

urlpatterns = [
    url(r'^login$', LoginView.as_view(), name='login'),
    url(r'^logout$', Logout.as_view(), name='logout'),
    # url(r'^signup$', 'django.contrib.admin.views.)
    # url('^signup$', AuthorCreate.as_view(), name='signup'),
    url(r'^signup$',
        CreateView.as_view(template_name="signup.html", form_class=AuthorCreate, success_url=settings.LOGIN_URL),
        name='signup'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^note/(?P<pk>\d+)$', NoteDetail.as_view(), name='note_detail'),
    url(r'^note/create$', NoteCreate.as_view(), name='note_create'),
    url(r'^note/(?P<pk>\d+)/comment$', CommentCreate.as_view(), name='comment'),
    url(r'^note/(?P<pk>\d+)/like$', Like.as_view(), name='like'),
    url(r'^author/(?P<pk>\d+)/profile', AuthorProfile.as_view(), name='profile'),
    url(r'^$', NotesList.as_view(), name='home')
]

blog/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Author(models.Model):
    user = models.OneToOneField(User, default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('profile', kwargs={"pk": self.id})

class Assessment(models.Model):
    author = models.ForeignKey(Author)
    # like or dislike
    attitude = models.BooleanField()

    class Meta:
        unique_together = (('author', 'attitude'),)


class Note(models.Model):
    title = models.CharField(max_length=255)
    code = models.TextField()
    description = models.TextField()
    time = models.DateTimeField(auto_now=True)
    # json comma-separated tags
    keywords = models.TextField()
    author = models.ForeignKey(Author)
    assessments = models.ManyToManyField(Assessment)

    def get_likes(self):
        return str(self.assessments.filter(attitude=True).count())

    def get_dislikes(self):
        return str(self.assessments.filter(attitude=False).count())

class Comment(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author)
    note = models.ForeignKey(Note)
    assessments = models.ManyToManyField(Assessment)

blog/myapp/forms.py
# from django import forms
# from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.models import User
# from .models import Author
#
#
# class AuthorCreate(UserCreationForm):
#         first_name=forms.CharField(required=False)
#         last_name=forms.CharField(required=False)
#         username=forms.CharField(required=True)
#         password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={"palceholder":"Password"}))
#         password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={"palceholder":"Confirm password"}))
#
#         def save(self):
#                 user=super(AuthorCreate, self).save()
#                 author=Author(nick_name=user)
#                 author.save()
#                 return author
#         class Meta:
#             model=User
#
# class Login(AuthenticationForm):
#         def __init__(self, *args, **kwargs):
#                 super(Login,self).__init__(*args,**kwargs)

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django import forms
from django.forms.models import model_to_dict, fields_for_model
from django.utils.html import strip_tags
from .models import Author, Note, Comment


class AuthorCreate(UserCreationForm):
    first_name = forms.CharField(required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}))
    last_name = forms.CharField(required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}))
    username = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'form-control'}))
    password1 = forms.CharField(label="Password", required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'form-control'}))
    password2 = forms.CharField(label="Password Again", required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password Confirmation', 'class': 'form-control'}))
    email = forms.CharField(required=True,
                            widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'username', 'password1',
                  'password2']
        model = User

    def is_valid(self):
        form = super(AuthorCreate, self).is_valid()
        for f, error in self.errors.items():
            if f != '__all__':
                self.fields[f].widget.attrs['data-toggle'] = 'tooltip'
                self.fields[f].widget.attrs['data-placement'] = 'right'
                self.fields[f].widget.attrs['title'] = error[0]

        return form

    def save(self):
        user = super(AuthorCreate, self).save()
        a = Author(user=user)
        a.save()
        return a


class Login(AuthenticationForm):
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'class': 'form-control login-field'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(
        attrs={'placeholder': 'Password', 'class': 'form-control login-field'}))

    def is_valid(self):
        form = super(AuthenticationForm, self).is_valid()
        for f, error in self.errors.items():
            if f != '__all__':
                self.fields[f].widget.attrs['data-toggle'] = 'tooltip'
                self.fields[f].widget.attrs['data-placement'] = 'right'
                self.fields[f].widget.attrs['title'] = error[0]
        return form


class NoteCreate(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'code', 'description', 'keywords']


class CommentCreate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

blog/myapp/views.py
import json
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, FormView, CreateView, RedirectView, DetailView
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.contrib.auth.models import *
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from .models import Note, Author, Comment, Assessment
from .forms import Login, NoteCreate, CommentCreate
from myapp import forms

import logging

logger = logging.getLogger('title')


class AuthorCreate(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    model = Author


class AuthorProfile(DetailView):
    model = Author
    template_name = 'myapp/author_profile.html'


class LoginView(FormView):
    form_class = Login
    success_url = reverse_lazy('home')
    template_name = 'login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)
            # def get(self, request, *args, **kwargs):
            #     next=request.GET['next']
            #
            # def get_context_data(self, **kwargs):
            #     context=super(FormView,self).
            #
            # def post(self, request, *args, **kwargs):
            #     redirect=request.POST['next']


def addTitle(get_title):
    def decorator(func):
        def wrapper(*args, **kwarg):
            context = func(*args, **kwarg)
            context['title'] = get_title()
            logger.debug(context['title'])
            return context

        return wrapper

    return decorator


class Logout(RedirectView):
    url = reverse_lazy('login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class NotesList(ListView):
    model = Note
    title = 'Notes'

    def get_title(self):
        def actual():
            return self.title

        return actual

    # @method_decorator(addTitle(get_title()))
    def get_context_data(self, **kwargs):
        # logger.debug(self.title)
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context

    def get_queryset(self):
        notes = super().get_queryset()
        # notes = Note.objects.all()
        query = self.request.GET.get('q')
        keyword = self.request.GET.get('kw')
        if query:
            notes = notes.filter(Q(title__icontains=query))
            self.title = 'Search results for "' + query + '"'
        elif keyword:
            notes = notes.filter(Q(keywords__regex=r'\b' + keyword + r'\b'))
            self.title = 'Notes that tagged by "' + keyword + '"'

        return notes


class NoteCreate(LoginRequiredMixin, CreateView):
    # redirect_field_name = ''
    form_class = NoteCreate
    template_name = 'myapp/note_create.html'
    model = Note
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = Author.objects.get(user=self.request.user)
        return super().form_valid(form)


class NoteDetail(DetailView):
    model = Note
    template_name = 'myapp/note_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = forms.CommentCreate
        context['title'] = self.object.title  # super().get_object().title
        # context['comments'] = Comment.objects.all().filter(note=self.object.pk)
        context['likes'] = self.object.assessments.filter(attitude=True)
        context['dislikes'] = self.object.assessments.filter(attitude=False)
        context['keywords'] = self.object.keywords.split(',')
        return context


class Like(LoginRequiredMixin, CreateView):
    model = Assessment

    def post(self, request, *args, **kwargs):
        result = 'added'
        try:
            # pk = int(request.POST.get('pk'))
            pk = self.kwargs['pk']
            note = get_object_or_404(Note, pk=pk)
            attitude = request.POST.get('attitude')
            if attitude == 'like':
                bool_attitude = True
            elif attitude == 'dislike':
                bool_attitude = False
            else:
                return HttpResponse(json.dumps({'result': 'error', 'message': "Invalid assessment type:" + attitude}),
                                    content_type="application/json")
            assessments = note.assessments
            same_attitude_assessments = assessments.filter(attitude=bool_attitude)
            author_assessments = assessments.filter(author=request.user.author)

            if author_assessments.filter(attitude=bool_attitude).exists():
                return HttpResponse(json.dumps({'result': 'unmodified'}), content_type="application/json")

            opposite_assessment = author_assessments.filter(attitude=not bool_attitude)
            if opposite_assessment.exists():
                note.assessments.remove(opposite_assessment.first())
                result = 'changed'
            assessment, _ = Assessment.objects.get_or_create(author=request.user.author, attitude=bool_attitude)
            # assessment.save()
            note.assessments.add(assessment)
            return HttpResponse(json.dumps({'result': result, 'count': same_attitude_assessments.count()}),
                                content_type="application/json")
        except ValueError:
            return HttpResponse(json.dumps({'result': 'error', 'message': "Invalid issue id!"}),
                                content_type="application/json")


class CommentCreate(LoginRequiredMixin, CreateView):
    form_class = CommentCreate
    # template_name = 'comment_create.html'
    model = Comment

    def get_success_url(self):
        return reverse('note_detail', kwargs={"pk": self.kwargs['pk']})

    def form_valid(self, form):
        form.instance.author = Author.objects.get(user=self.request.user)
        form.instance.note = Note.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)
        # return HttpResponseRedirect('/')

# Create your views here.

blog/myapp/templates/myapp/author_profile.html
{% extends 'base.html' %}
{% block content %}
    <p>Nickname:{{ object.user.username }}</p>
    <p>First name:{{ object.user.first_name }}</p>
    <p>Last name:{{ object.user.last_name }}</p>
    <p>Signed up:{{ object.created_at }}</p>
{% endblock %}

blog/myapp/templates/myapp/base_header.html
{#{% extends 'base.html' %}#}

{% block header %}
    <header>
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'home' %}">CodeNote</a>
                    </div>

                    {% comment %}                <form id="nav-search" class="navbar-form navbar-right" role="search">
                        <input type="text" class="form-control" placeholder="Search">
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </form>{% endcomment %}
                    <div class="row">
                        <div class="col-xs-4 navbar-right">
                            {% if user.is_authenticated %}
                                <a href={% url 'logout' %}>
                                    <button class="btn btn-success navbar-btn" type="button">Sign out</button>
                                </a>
                                <a href="{% url 'profile' pk=user.author.id %}" id="username">{{ user.username }}</a>
                            {% else %}
                                <a href={% url 'login' %}>
                                    <button class="btn btn-success navbar-btn" type="button">Sign in</button>
                                </a>
                                <a href={% url 'signup' %}>
                                    <button class="btn btn-success navbar-btn" type="button">Sign up</button>
                                </a>
                            {% endif %}
                            <form class="navbar-form navbar-left" role="search" action="{% url 'home' %}" method="get">
                                <div class="input-group">
                                    <input type="text" name="q" class="form-control" placeholder="Search">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-default">
                                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                        </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

blog/myapp/templates/myapp/comment_create.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Ok">
    </form>
{% endblock %}

blog/myapp/templates/myapp/note_create.html
{% extends 'base.html' %}
{% block content %}
    <form action="" , method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" , value="Save">
    </form>
{% endblock %}

blog/myapp/templates/myapp/note_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ object.title }}</h1>
    <pre>{{ object.code }}</pre>
    {% for keyword in keywords %}
        <a href="{% url 'home' %}?kw={{ keyword | urlencode }}">#{{ keyword }} </a>
    {% endfor %}
    <ul>
        {% for comment in object.comment_set.all %}
            <li>
                <a href="{{ comment.author.get_absolute_url }}">{{ comment.author.user.first_name | title }} {{ comment.author.user.last_name | title }}</a>:{{ comment.text }}
            </li>
        {% endfor %}
    </ul>

    <span class="likes">
        <button type="button" class="btn btn-default btn-lg like">
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            <text>{{ likes.count }}</text>
        </button>
        <button type="button" class="btn btn-default btn-lg dislike">
            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
            <text>{{ dislikes.count }}</text>
        </button>
    </span>
    <form action="{% url 'comment' pk=object.pk %}" method="post">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="Send comment">
    </form>
{% endblock %}

blog/myapp/templates/myapp/note_list.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ title }}</h1>
    <a href="{% url 'note_create' %}">Create note</a>
    <ul>
        {% for note in object_list %}
            <li><a href="/note/{{ note.pk }}">{{ note.title }}</a>
                <text>{{ note.comment_set.count }} comments</text>
                <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                <text>{{ note.get_likes }}</text>
                <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                <text>{{ note.get_dislikes }}</text>
            </li>
        {% empty %}
            <li>No notes yet</li>
        {% endfor %}
    </ul>
{% endblock %}